#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=65
STOP=65

USE_PROCD=1
PROG=/sbin/ntpd

start_service() {
	mkdir -p /var/lib/ntp

	procd_open_instance
	procd_set_param command $PROG -g -u ntp:ntp -p /var/run/ntpd.pid -n -q
	procd_close_instance
}
